config/ilm/* /usr/lib/perfsonar/archive/config/ilm/
config/roles/* /usr/lib/perfsonar/archive/config/roles/
config/users/* /usr/lib/perfsonar/archive/config/users/
config/index_template-pscheduler.json /usr/lib/perfsonar/archive/config/
config/index_template-auditlog.json /usr/lib/perfsonar/archive/config/
config/index_template-opendistro-ism.json /usr/lib/perfsonar/archive/config/
config/apache/* /etc/apache2/conf-available/
opensearch-scripts/* /usr/lib/perfsonar/archive/perfsonar-scripts/